### ISSUE TITLE
Uploading with app-store-connect and `--max-build-processing-wait 0` results in non-zero exit code

### ISSUE THREAD

**Issue by definitelyokay** [codemagic-ci-cd/cli-tools#202]
I've noticed that passing in `--max-build-processing-wait 0` to `app-store-connect` results in a non-zero completion code. I would think that if I deliberately request to skip waiting on processing, the command should succeed after uploading. Is this line of thinking correct?

```shell
app-store-connect publish \
  --path build/ios/ipa/*.ipa \
  --max-build-processing-wait 0 \
  --testflight
```

<img width="973" alt="Screen Shot 2022-02-13 at 12 38 08 AM" src="https://user-images.githubusercontent.com/16472250/153742265-dc8a2058-e69f-4852-8310-bd95e259af2a.png">

**Comment by priitlatt** [comment]
To add to the previous comment, it looks from the screenshot that everything is in fact correct - uploaded build is discovered in `PROCESSING` state, and since hard limit to max processing duration is set to 0 minutes, all further actions are terminated as the allowed timespan to wait until processing completes (and futher operations can be done) runs out.

**Comment by priitlatt** [comment]
Thanks for a quick reply. I'll close this issue for now.
