### ISSUE TITLE
Remove existing builds from review with `publish`

### ISSUE THREAD

**Issue by kevmo314** [codemagic-ci-cd/cli-tools#288]
Is it possible to remove any pending builds from review with the `publish` command? We end up having a decent number of builds get rejected because there's already a build pending for review which makes our testflight not match the latest version.

**Comment by kevmo314** [comment]
This would be similar to fastlane's `reject_if_possible`: http://docs.fastlane.tools/actions/upload_to_app_store/#upload_to_app_store

**Comment by priitlatt** [comment]
Hi @kevmo314, thanks for bringing this up. This sure sounds like a useful addition to `app-store-connect publish`. We'll give it some more thought on how to implement it and let you know. But please note that as of now I'm not yet able to give any ETA for it.

**Comment by VeArnold** [comment]
@kevmo314 

Hi! :)

Good proposal. However, to understand the aims and goals better, based on your description, it seems that the more fitting extension would be equivalent to Fastlane's `reject_build_waiting_for_review` instead of `expire_previous_builds`.

Please correct me if I am missing something. Thanks! :)

**Comment by kevmo314** [comment]
Yeah that's probably correct. We run publish as our last CI/CD step right now and it fails due to an existing build being in review (both testflight and app store) so the ideal behavior would be to be able to unmark the older builds
